public class CalculatorStaticJuly24 {
    
    public static void sumOfNumbers(integer num1, integer num2){
        
        integer sum;
        sum = num1+num2;
        system.debug('Sum of numbers will be '+sum);
    }
    public static void subOfNumbers(integer num1, integer num2){
        
        integer sub;
        sub = num1-num2;
        system.debug('Sub of numbers will be '+sub);
    }
    public static void mulOfNumbers(integer num1, integer num2){
        
        integer mul;
        mul = num1*num2;
        system.debug('Mul of numbers will be '+mul);
    }
    public static void divOfNumbers(integer num1, integer num2){
        
        integer div;
        div = num1/num2;
        system.debug('Sum of numbers will be '+div);
    }

}

/*
 * CalculatorStaticJuly24.sumOfNumbers(11,22);
CalculatorStaticJuly24.subOfNumbers(11,22);
CalculatorStaticJuly24.mulOfNumbers(11,22);
CalculatorStaticJuly24.divOfNumbers(11,22);*/
