public class CircleStaticJuly24 {
    
    public static void areaOfCircle(decimal radius){
        
        decimal area;
        area = 3.14*radius*radius;
        system.debug('area of circle is '+ area);
    }
    
    public static void periOfCircle(decimal radius){
        
        decimal Perimeter;
        Perimeter = 2*3.14*radius;
        system.debug('area of circle is '+ Perimeter);
    }
    

}
//thisi is to call the methods and class ffor output.
//CircleStaticJuly24.areaOfcircle(11);
//CircleStaticJuly24.periOfCircle(11);
