public class LoopDemoJuly24 {
    
    public static void nameTenTimes(){
        
        for(integer i = 1; i<=10; i++){
            system.debug('My name is Batman');
        }
        system.debug('**************');
    }
    
    public static void nameUserGivenTimes(integer num){
        for(integer i  =1  ; i<= num ; i++){
            system.debug('My name is shaktiman');
        }
    }

}
