public class MaxOfTwoStaticJuly24 {
    
    public static void maxOfTwo(integer num1,  integer num2){
        
        if(num1>num2){
            system.debug('Num1 is greater then num2');
        }else{
            system.debug('num2 is greater then num1');
        }
    }
    
    public static void minOfTwo(integer num1,  integer num2){
        
        if(num1<num2){
            system.debug('Num1 is lesser then num2');
        }else{
            system.debug('num2 is lesser then num1');
        }
    }
    

}

//calling
//MaxOfTwoStaticJuly24.maxOfTwo(11,21);
//MaxOfTwoStaticJuly24.minOfTwo(32,33);
