public class PositiveNegORzeroJuly24 {
    
    public static void checkNumber(integer num){
        
        if(num>0){
            system.debug('Number is positive');
            
        }else if(num == 0){
            system.debug('number is zero');
            
        }else{
            system.debug('Number is negative');
        }
    }

}
//to call = PositiveNegORzeroJuly24.checkNumber(0);
