public class RectangleStaticJuly24 {
    
    public static void areaOfRectangle(integer length, integer width){
        
        integer area;
        area = length*width;
        system.debug('Area os rectangle is '+ area);
    }
    
    public static void periOfRectangle(integer length, integer width){
        
        integer Perimeter;
        Perimeter = 2*(length+width);
        system.debug('Area os rectangle is '+ Perimeter);
    }

}

//RectangleStaticJuly24.areaOfRectangle(10,20);
//RectangleStaticJuly24.periOfRectangle(2,9);
